# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Albert Nafría Febrer
tagline:          'My personal Blog'
description:      'I am a software developer with a passion for cybersecurity'
url:              https://blog.albertnafria.dev
baseurl:          /

author:
  name:           'Albert Nafría'
  url:            https://albertnafria.dev

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/AlbertNafria
